server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    secure-port-enabled: false
    non-secure-port-enabled: true