server:
  port: ${SERVER_PORT:9000}

spring:
  application:
    name: authentication-service

security:
  jwt:
    secret: ${JWT_SECRET:uQw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw==}
    expiration: ${JWT_EXPIRATION:3600000}

logging:
  level:
    com.rahim: DEBUG
    org.springframework: INFO

