server:
  port: ${SERVER_PORT:9999}

spring:
  application:
    name: authentication-service

jwt:
  secret: SOME_VERY_LONG_KEY_THAT_I_NEED_TO_CHANGE
  expiration:
    ms: 86400000

verification:
  email:
    expiration-minutes: 30
  code:
    length: 6
  max-attempts: 5

logging:
  level:
    com.rahim: DEBUG
    org.springframework: INFO