server:
  port: ${SERVER_PORT:9000}

spring:
  application:
    name: authentication-service

  flyway:
    table: flyway_authentication_service_history

logging:
  level:
    com.rahim: DEBUG
    org.springframework: INFO

