spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: '{cipher}b6d59072142ba74dfcd6ad83b802ffc0d3c85d4cb645a88c8e03ae2ea841510f76af5fca4359335741a4cae633285ac5db5a9288a5040ac30291ae3ab360f93c'
    username: '{cipher}ac09d5514be7de857462e6c8711037c5e1b3a1864db3ff9390c67f2f07978a01'
    password: '{cipher}8945a03544d4b5f8d836a12d5cb1ff265aebb8d23ff3cd56609e76ea6bb7d2f6'
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
