server:
  port: 8083

spring:
  application:
    name: email-service
  mail:
    host: localhost
    port: 1025
    username: '{cipher}242b15b8a6e0cf1db2c00f4e91d7d408c76e193bde8bef1cbc1d250ca52e48a4f18c716405840e06ebd1ab51eeb9fb7e'
    password: '{cipher}ab34a8a4455cfa501b5ad9c14e7b418c7299fe4353ade32581a4eeb367737b88'
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    com.rahim.emailservice: DEBUG
    org.springframework: INFO