server:
  port: 8083

spring:
  application:
    name: email-service
  mail:
    host: localhost
    port: 1025
    username: rahim1605@gmail.com
    password: ''
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    com.rahim.emailservice: DEBUG
    org.springframework: INFO