server:
  port: 8083

spring:
  application:
    name: email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SERVICE_USERNAME}
    password: ${EMAIL_SERVICE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.rahim.emailservice: DEBUG
    org.springframework: INFO