eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    secure-port-enabled: false
    non-secure-port-enabled: true