spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    clean-disabled: false
    schemas: ${spring.application.name}
    default-schema: ${spring.application.name}