security:
  jwt:
    secret: ${JWT_SECRET:uQw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw1v6Qw==}
    expiration: ${JWT_EXPIRATION:1800000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}