kafka:
  security-protocol: PLAINTEXT
  bootstrap-servers: '{cipher}b579b40298eb78f2721361db62b0d4ee1a9e5a75ca2acb844a577850ff9c73cd'
  ssl:
    key-store-location: file://location-to-keystore-file
    key-password: '{cipher}password'
    trust-store-location: file://location-to-truststore-file
    trust-store-password: '{cipher}password'
    protocol: TLSv1.2
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  consumer:
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer