server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: pricing-service

  flyway:
    table: flyway_pricing_service_history

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.rahim: DEBUG
    org.springframework: INFO

