// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: price.proto
// Protobuf Java Version: 4.29.1

package com.rahim.proto.protobuf;

public interface GoldPriceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rahim.proto.protobuf.GoldPriceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string source = 1;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <code>string source = 1;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>float price = 2;</code>
   * @return The price.
   */
  float getPrice();

  /**
   * <code>string datetime = 3;</code>
   * @return The datetime.
   */
  java.lang.String getDatetime();
  /**
   * <code>string datetime = 3;</code>
   * @return The bytes for datetime.
   */
  com.google.protobuf.ByteString
      getDatetimeBytes();
}
