// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: price.proto
// Protobuf Java Version: 4.29.1

package com.rahim.proto.protobuf;

public final class Price {
  private Price() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      Price.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rahim_proto_protobuf_GoldPriceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_rahim_proto_protobuf_GoldPriceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013price.proto\022\030com.rahim.proto.protobuf\032" +
      "\033google/protobuf/empty.proto\"D\n\021GoldPric" +
      "eResponse\022\016\n\006source\030\001 \001(\t\022\r\n\005price\030\002 \001(\002" +
      "\022\020\n\010datetime\030\003 \001(\t2g\n\020GoldPriceService\022S" +
      "\n\014GetGoldPrice\022\026.google.protobuf.Empty\032+" +
      ".com.rahim.proto.protobuf.GoldPriceRespo" +
      "nseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_com_rahim_proto_protobuf_GoldPriceResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_rahim_proto_protobuf_GoldPriceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_rahim_proto_protobuf_GoldPriceResponse_descriptor,
        new java.lang.String[] { "Source", "Price", "Datetime", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
