#!/bin/sh

# Array of modules to format
MODULES=(
    "rgts-common"
    "rgts-kafka-service"
    "rgts-pricing-service"
    "rgts-proto-service"
)

# Find changed modules
CHANGED_MODULES=()
for module in "${MODULES[@]}"; do
    if git diff --cached --name-only | grep -q "^${module}/"; then
        CHANGED_MODULES+=("$module")
    fi
done

# If no changed modules, exit
if [ ${#CHANGED_MODULES[@]} -eq 0 ]; then
    exit 0
fi

# Format changed modules
for module in "${CHANGED_MODULES[@]}"; do
    echo "Formatting $module..."
    (
        cd "$module" && \
        mvn -B com.spotify.fmt:fmt-maven-plugin:format
    )

    # Stage formatted files
    git add "$module"
done

exit 0