name: Build Code, Test and Build to Docker
on:
  push:
    branches:
      - main
    paths:
      - 'rgts-common/**'
      - 'rgts-proto-service/**'
      - 'rgts-kafka-service/**'
      - 'rgts-pricing-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [
          "rgts-common",
          "rgts-proto-service",
          "rgts-kafka-service",
          "rgts-pricing-service"
        ]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build parent Maven
        run: mvn clean install

      # Sequential steps for each matrix.folder
      - name: Build with Maven for ${{ matrix.folder }}
        run: |
          echo "Building ${{ matrix.folder }} folder"
          cd ${{ matrix.folder }}
          mvn clean install

      # Log in to Docker Hub (Uncomment if needed)
      # - name: Log in to Docker Hub
      #   if: env.ENABLE_BUILD != 'false'
      #   run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Build and push Docker image (Uncomment if needed)
      # - name: Build and push Docker image for ${{ matrix.folder }}
      #   if: env.changed == 'true' && env.ENABLE_BUILD != 'false'
      #   run: |
      #     docker build -t rahimahmed/${{ matrix.folder }} -f ${{ matrix.folder }}/Dockerfile .
      #     docker push rahimahmed/${{ matrix.folder }}
