name: Build Code, Format, Commit and Push Image to Docker

on:
  push:
    branches:
      - main
    paths:
      - 'rgts-common/**'
      - 'rgts-kafka-service/**'
      - 'rgts-pricing-service/**'
      - 'rgts-proto-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [
          "rgts-common",
          "rgts-kafka-service",
          "rgts-pricing-service",
          "rgts-proto-service"
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up environment variables
        run: |
          changes=$(git diff --name-only HEAD^ HEAD "${{ matrix.folder }}")
          echo "changes=$changes" >> $GITHUB_ENV

      - name: Build with Maven
        if: env.ENABLE_BUILD != 'false'
        run: mvn clean install

      - name: Format Java Code
        run: |
          mvn -B com.spotify.fmt:fmt-maven-plugin:format
        working-directory: ${{ matrix.folder }}

      - name: Commit formatted code
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout ${{ github.head_ref || github.ref_name }}
          git add .
          git commit -m "Apply code formatting for ${{ matrix.folder }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} ${{ github.head_ref || github.ref_name }}

      # - name: Log in to Docker Hub
      #   if: env.ENABLE_BUILD != 'false'
      #   run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # - name: Build and push Docker image
      #   if: env.changed == 'true' && env.ENABLE_BUILD != 'false'
      #   run: |
      #     docker build -t rahimahmed/${{ matrix.folder }} -f ${{ matrix.folder }}/Dockerfile .
      #     docker push rahimahmed/${{ matrix.folder }}
